bugfixes: fix build failure and Bug #189357
- gpy fails with an error
    ImportError: This platform lacks a functioning sem_open implementation,
    therefore, the required synchronization primitives needed will not function,
    see issue 3770.
  and build fails.

- the patch posted to https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=189357
  has not been applied yet.